### ISSUE TITLE
Requesting content removal regarding to violating of GPL and MIT license/要求移除违反开源协议之部分

### ISSUE THREAD

**Issue by cnbeining** [fuckbilibili/fuckbilibili.github.io#10]
To whom it may concern,

I, the original author, have good faith that this repository has violated several of my projects' license, including GPL or MIT.

Pages related:

http://www.fuckbilibili.com/srt2bilibili.html

http://www.fuckbilibili.com/bililivesilver.html

http://www.fuckbilibili.com/livenumber.html

http://www.fuckbilibili.com/bilidown.html

http://www.fuckbilibili.com/404page.html

Files related:

https://github.com/fuckbilibili/fuckbilibili.github.io/blob/gh-pages/articles/bililivesilver.md

https://github.com/fuckbilibili/fuckbilibili.github.io/blob/gh-pages/articles/livenumber.md

https://github.com/fuckbilibili/fuckbilibili.github.io/blob/gh-pages/articles/srt2bilibili.md

https://github.com/fuckbilibili/fuckbilibili.github.io/blob/gh-pages/articles/bilidown.md

https://github.com/fuckbilibili/fuckbilibili.github.io/blob/gh-pages/articles/about404.md

I hereby request files and pages related being removed in 24 hours.

Yours Sincerely,
Beining

**Comment by hanbang-wang** [comment]
抱歉 改的时候把署名去了

**Comment by hanbang-wang** [comment]
ok了
