### ISSUE TITLE
评论: 为什么我们想要做这个网站？

### ISSUE THREAD

**Issue by Ray1011** [fuckbilibili/fuckbilibili.github.io#2]
目前正利用某些api进行爬番，正做了一个追番打卡应用，不知道有兴趣合作吗？

**Comment by hanbang-wang** [comment]
小心版权问题哦，这个东西vespa好像有在做……
什么平台上的？

**Comment by cnbeining** [comment]
我不认为这个会有什么大的版权问题。

API都是公开的，慢点爬不会死。
